Add FAQs and repo documentation
Quansight-Labs/jupyter-communitycalls pull request #21
Opened 2021-07-26 23:24 UTC by isabela-pf

A PR adding information about this repo so it can be shared more publicly.
- [x] Add FAQ content
- [ ] Add "how to use this repo" documentation
- [ ] Add images for documentation

Fixes #16

2021-07-30 23:58 UTC, isabela-pf commented
@tonyfast @goanpeca If either of you are interested in reviewing this documentation, I'd be happy to hear the feedback.

2021-08-09 17:30 UTC, goanpeca commented on faqs.md
> +-  Your favorite Jupyter notebook(s)
Extra space

2021-08-09 17:31 UTC, goanpeca commented on faqs.md
> +- Something we’ve never seen before
Maybe it would be nice to say something like:

- Showcase how you use a particular Jupyterlab extension.
- Showcase a new extension you develope for Jupyterlab.

2021-08-09 17:31 UTC, goanpeca commented on faqs.md
> +It is also good practice to keep your mic muted when you are not talking
mic -> microphone

2021-08-09 17:32 UTC, goanpeca commented on faqs.md
> + [how to use the repo here]().
Missing link?

2021-08-09 17:38 UTC, goanpeca commented on how-to-use-this-repo.md
> +This repository is for you to have a central place that stores up-to-date Jupyter community call info and resources. [`readme.md`](https://github.com/Quansight-Labs/jupyter-communitycalls/#readme) is
Usually `README.md`. is upper cased

2021-08-09 17:38 UTC, goanpeca commented on how-to-use-this-repo.md
> +This repository has resources to support community call planning. The [For Hosts](https://github.com/Quansight-Labs/jupyter-communitycalls/#for-hosts) section of the `readme` has files that may help
`README`

2021-08-09 17:39 UTC, goanpeca commented on how-to-use-this-repo.md
> +**1. Edit `readme.md`**
a Bulleted list can be written as 

`1. ......`

2021-08-09 17:40 UTC, goanpeca requested changes
Hi @isabela-pf thanks a lot for workin on this. Apologies on the delay reviewing it.

Left a couple of comments and suggestions

2021-08-18 16:46 UTC, isabela-pf commented on how-to-use-this-repo.md
> +This repository is for you to have a central place that stores up-to-date Jupyter community call info and resources. [`readme.md`](https://github.com/Quansight-Labs/jupyter-communitycalls/#readme) is
True. I just get tired of being yelled at. I'll change it to all-caps though.

2021-08-18 16:53 UTC, isabela-pf commented on how-to-use-this-repo.md
> +**1. Edit `readme.md`**
Yes, I thought that would be messy with multiple paragraphs coming after it. I'll change it to be headings so that there is clarity for it similar to an ordered list.

2021-08-18 17:13 UTC, isabela-pf commented
Thanks for the review @goanpeca! I think I'm going to merge this PR with the upcoming August community call so that this repo feels more complete. I'm always open to more edits before or after then.

2021-08-18 17:19 UTC, goanpeca approved these changes
Thanks @isabela-pf ! 🚀

2021-09-03 18:53 UTC, merged